export enum RequestType{
    CONNECT = "CONNECT",
    
}

export enum MessageType{
    USER_CONNECTED = "USER_CONNECTED"
}

export enum ResponseType{
    SERVER_RESPONSE = "SERVER_RESPONSE",
    CONNECT_RESPONSE = "CONNECT_RESPONSE"
}

export enum ErrorType{
    INVALID_PAYLOAD = "INVALID_PAYLOAD",
    NON_JSON_FORMAT = "NON_JSON_FORMAT",
    INVALID_REQUEST_PARAMETERS = "INVALID_REQUEST_PARAMETERS",
    UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST"
}